---
plugins:
  checkstyle:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  nodesecurity:
    enabled: true    
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: true
      Mass:
        enabled: true
    config:
      languages:
      - javascript
exclude_patterns:
- __tests__/
- tests/
- node_modules/
- coverage/