language: node_js

node_js:
  - "stable"

#services:
#  - mongodb

cache:
  directories:
    - "server/node_modules"

install:
  - npm --prefix app install
  - npm --prefix server install

#before_script:
#  - sleep 15
#  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test-ci --prefix app
  - npm run test-ci --prefix server

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -p ./server/coverage --debug
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

