# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "9a6ef954-a397-48be-b442-19b2ea2745a5"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
#  ensure_git_status_clean
#  increment_version_code
#  commit_android_version_bump
#  push_to_git_remote

  # build the release variant
  gradle(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    # keys for organization: SCVsoft
    api_token: "45178e641f4bbd9b777cedd7484c5dd9879362ad",
    build_secret: "abac4e20f08bce38ec99b563cfe3ce39fdbbdb568dae0ee3da0bfd404fface1d",
    groups: "Temis"
  )
end