#!/usr/bin/env bash
set -e

# update instance
yum install -y yum-utils
yum-config-manager --enable rhui-us-east-2-rhel-server-extras rhui-us-east-2-rhel-server-optional

yum update -y

# install nginx
if [ -e /etc/init.d/httpd ]; then
	service httpd stop
	chkconfig httpd off
fi
yum remove -y httpd
yum install -y nginx
chkconfig nginx on

# setup nginx
mkdir --parent /home/ec2-user/temis/server/logs/

cat <<EOF>/etc/nginx/conf.d/temis.conf
# Redirect HTTP traffic to HTTPS
server {
    listen 80;
    server_name api.temis.care;
    access_log off;
    error_log off;
        return 301 https://api.temis.care$request_uri;
    }
# Handle https://api.temis.care
server {
    listen 443 ssl http2;
    server_name api.temis.care;
    ssl on;
    ssl_ciphers  EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:EDH+aRSA:HIGH:!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!SEED:!DSS:!CAMELLIA;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 5m;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_certificate      /etc/letsencrypt/live/api.temis.care/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/api.temis.care/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/api.temis.care/chain.pem;
    ssl_dhparam /etc/letsencrypt/dhparams.pem; # Generated by running "openssl dhparam -out /etc/letsencrypt/dhparams.pem 2048" as root user
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block"; 
    resolver 8.8.8.8;

    access_log /home/ec2-user/temis/server/logs/access.log main;
    error_log /home/ec2-user/temis/server/logs/error.log warn;
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF

# SSL
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto
mv certbot-auto /usr/bin/
certbot-auto certonly \
  --standalone \
  --agree-tos \
  --non-interactive \
  --text \
  --rsa-key-size 4096 \
  --email peter@temis.care \
  --domains "api.temis.care"

openssl dhparam -out /etc/letsencrypt/dhparams.pem 2048

cat <<EOF>/etc/cron.daily/certbot-renewal
#!/bin/bash
#
# Renew the Let's Encrypt certificate if it is time.
 
# Using --no-self-upgrade suppresses the automatic update check that
# might not work in a cron context.
certbot-auto --no-self-upgrade certonly
 
# Update all of the services that might now need to be using the renewed 
# certificate.
service nginx reload
EOF

# install mongo
cat <<EOF>/etc/yum.repos.d/mongodb-org-3.0.repo
[mongodb-org-3.0]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.0/x86_64/
gpgcheck=0
enabled=1
EOF

yum install -y mongodb-org
service mongod start

# add nodejs to yum
curl --silent --location https://rpm.nodesource.com/setup_9.x | bash -
yum install -y nodejs

# install pm2 module globaly
npm install -g pm2
env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemv -u ec2-user --hp /home/ec2-user
pm2 update